<?php

namespace AppBundle\Repository;

/**
 * OneToManyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneToManyRepository extends \Doctrine\ORM\EntityRepository
{
}
