<?php

namespace AppBundle\Repository;

/**
 * OneToOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneToOneRepository extends \Doctrine\ORM\EntityRepository
{
}
