imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: mysql
        connections:
            mysql:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%databasetest_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
            pgsql:
                driver: pdo_pgsql
                host: '%psql_database_host%'
                port: '%psql_database_port%'
                dbname: '%psql_databasetest_name%'
                user: '%psql_database_user%'
                password: '%psql_database_password%'
                charset: UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #path: '%database_path%'


    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true