AppBundle\Entity\OneToOne:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\OneToOneRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
  oneToOne:
    one:
      targetEntity: AppBundle\Entity\One
      joinColumn:
        name: one_id
        referencedColumnName: id

  lifecycleCallbacks: {  }
